- name: mysql-component
  hosts: mysql
  become: yes
  tasks:
    - name: disable MySQL 8 version
      ansible.builtin.command: yum module disable mysql -y
    - name: copy file /mysql.repo to /etc/yum.repos.d/mysql.repo
      ansible.builtin.copy:
        src: /etc/yum.repos.d/mysql.repo
        dest: /mysql.repo
    - name: Install MySQL Server
      ansible.builtin.yum:
        name: mysql-community-server
        state: installed
    - name: start mysqld
      ansible.builtin.service:
        name: mysqld
        state: started
        enabled: yes
    - name: default root password
      ansible.builtin.command: mysql_secure_installation --set-root-pass RoboShop@1
    - name: new password
      ansible.builtin.command: mysql -uroot -pRoboShop@1
